spring:
  application:
    name: department-service
  datasource:
    url: jdbc:mysql://localhost:3306/department_service?useSSL=false
    username: shubham
    password: shubham
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: "optional:configserver:http://localhost:8088"
